# Generated by Django 5.2.7 on 2025-11-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='route_maps/', verbose_name='Карта маршрута'),
        ),
    ]
