# Generated by Django 5.2.7 on 2025-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_map', '0002_route_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='line_color',
            field=models.CharField(default='#3388ff', help_text='HEX цвет, например #ff0000 для красного', max_length=7, verbose_name='Цвет линии'),
        ),
        migrations.AddField(
            model_name='route',
            name='line_opacity',
            field=models.FloatField(default=0.7, help_text='От 0.0 (полностью прозрачно) до 1.0 (непрозрачно)', verbose_name='Прозрачность линии'),
        ),
        migrations.AddField(
            model_name='route',
            name='line_width',
            field=models.IntegerField(default=3, help_text='Толщина линии на карте (1-10 пикселей)', verbose_name='Толщина линии'),
        ),
    ]
